version: '3.8'

services:
  backend:
    build: .
    container_name: backend
    ports:
      - 8080:8080
    volumes:
      - .env:/app/.env
    env_file:
      - ./.env
    depends_on:
      - mongodb
    links:
      - redis
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - data:/data/db
    ports:
      - 27017:27017
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports: 
      - 6379:6379

volumes:
  data: